# Generated by Django 3.0.6 on 2020-06-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espaces', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='plan',
        ),
    ]
