# Generated by Django 3.0.6 on 2020-05-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
