# Generated by Django 3.0.6 on 2020-06-08 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.CharField(default='2020-06-07T23:44:46.814882Z', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=20),
        ),
    ]
